#!/bin/bash
# Auto-generated by bareme.nvim

WORKTREE_BRANCH='main'

echo "{\"worktree\":\"$WORKTREE_BRANCH\",\"event\":\"needs_input\",\"timestamp\":$(date +%s)}" >> ~/.local/state/bareme/claude_events.jsonl
