#!/bin/bash
# Auto-generated by bareme.nvim

WORKTREE_PATH='/Users/nerap/personal/bareme.nvim.git/main'
WORKTREE_BRANCH='main'
MESSAGE_TYPE="$1"
MESSAGE_COUNT="$2"

echo "{\"worktree\":\"$WORKTREE_BRANCH\",\"path\":\"$WORKTREE_PATH\",\"event\":\"message\",\"type\":\"$MESSAGE_TYPE\",\"count\":$MESSAGE_COUNT,\"timestamp\":$(date +%s)}" >> ~/.local/state/bareme/claude_events.jsonl
